
# platform :ios, '9.0'
platform:ios,'9.0'

inhibit_all_warnings!
target 'HuanXingKefuDemo' do
  
  pod 'JPush'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'MWPhotoBrowser'
  
end

target 'NotificationServiceTest' do
  pod 'JPushExtension'
end
